=== BackupTheBerlios/umlvim/Despe/WEB-INF/planningConf.dtd
<!ELEMENT planning (month*)>

<!ELEMENT month (day*)>
<!ATTLIST month number CDATA #REQUIRED>


<!ELEMENT day (morning?,afternoon?)>
<!ATTLIST day  number CDATA #REQUIRED>


<!ELEMENT morning (beginingHour,endHour)>
<!ATTLIST morning  correctorNumber CDATA #REQUIRED
				   meetingDuration CDATA #REQUIRED
				   ravelNumber CDATA #REQUIRED>

<!ELEMENT afternoon (beginingHour,endHour)>
<!ATTLIST afternoon  correctorNumber CDATA #REQUIRED
					 meetingDuration CDATA #REQUIRED
					 ravelNumber CDATA #REQUIRED>
	
<!ELEMENT endHour (Hour)>

<!ELEMENT beginingHour (Hour)>

<!ELEMENT Hour (#PCDATA)>
<!ATTLIST Hour hour CDATA #REQUIRED
			   min  CDATA #REQUIRED>

=== BackupTheBerlios/umlvim/Despe/WEB-INF/planningConf.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE planning SYSTEM "workspace/despe/WEB-INF/planningConf.dtd">

<planning>
	<month number="11">
		<day number="14">
			<morning correctorNumber="20" meetingDuration="20" ravelNumber="10">
				<beginingHour>
					<Hour hour="8" min="0" />
				</beginingHour>
				<endHour>
					<Hour hour="10" min="0" />
				</endHour>
			</morning>
			<afternoon correctorNumber="20" meetingDuration="20" ravelNumber="10">
<beginingHour><Hour hour="2" min="0" /></beginingHour>
<endHour><Hour hour="3" min="0" /></endHour>
</afternoon>
</day><day number="15">
<morning correctorNumber="20" meetingDuration="20" ravelNumber="10">
<beginingHour><Hour hour="8" min="0" /></beginingHour>
<endHour><Hour hour="10" min="0" /></endHour>
</morning><afternoon correctorNumber="20" meetingDuration="20" ravelNumber="10">
<beginingHour><Hour hour="2" min="0" /></beginingHour>
<endHour><Hour hour="3" min="0" /></endHour>
</afternoon>
</day></month></planning>
